services:
  dhlottery-lotto-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dhlottery-auto-lotto-bot
    restart: unless-stopped
    
    # 환경 변수 설정
    environment:
      - TZ=Asia/Seoul
      # .env 파일에서 환경 변수 로드
    env_file:
      - .env
    
    # 볼륨 마운트
    volumes:
      # 스크린샷 저장을 위한 볼륨
      - ./screenshots:/app/screenshots
      # 로그 저장을 위한 볼륨 (선택사항)
      - ./logs:/app/logs
    
    # 리소스 제한 (선택사항)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    # 네트워크 설정 (필요시)
    # networks:
    #   - dhlottery-network
    
    # 로그 설정
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 헬스체크 (Dockerfile에서 정의된 것을 오버라이드)
    healthcheck:
      test: ["CMD", "pgrep", "-f", "dhlottery-bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# 네트워크 정의 (필요시)
# networks:
#   dhlottery-network:
#     driver: bridge

# 볼륨 정의 (영구 저장이 필요한 경우)
volumes:
  screenshots:
    driver: local
  logs:
    driver: local 